### ISSUE TITLE
 Module '"../node_modules/yodlee-react-hook"' has no exported member 'useYodlee'

### ISSUE THREAD

**Issue by jmadan** [erhangundogan/yodlee-react-hook#1]
Post installing through following command
yarn add yodlee-react-hook

When I import the useYodlee hook as import { useYodlee } from 'yodlee-react-hook';

I get the following error
error TS2305: Module '"../node_modules/yodlee-react-hook"' has no exported member 'useYodlee'

below code in MyComponent.tsx

`import React from 'react';
import { useYodlee } from 'yodlee-react-hook';

const MyComponent = () => {
    const { ready, init } = useYodlee({
      containerId: 'container-fastlink',
      fastLinkOptions: {
        fastLinkURL: 'https://node.sandbox.yodlee.com/authenticate/restserver',
        token: {
          tokenType: 'AccessToken',
          tokenValue: 'foo'
        }
      }
    });
   
    return (
      <div className="container">
        <div id="container-fastlink"></div>
        { ready ? <button onClick={() => init()}>Open Yodlee</button> : 'Loading...' }
      </div>
    );
  }`

package.json

`
{
  "name": "yodlee-poc",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "reac": "^0.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "typescript": "^4.1.2",
    "yodlee-react-hook": "^0.2.0"
  }
}
`

**Comment by erhangundogan** [comment]
@jmadan thanks for creating issue and your feedback. 

Regarding to your problem it seems you cannot able to import ES module into the app. I can only think of a problem in your configuration since it cannot import installed NPM module. Please try fresh create-react-app instance with the steps below:
- `npx create-react-app yodlee-test`
- `yarn add yodlee-react-hook`
- replace App component with the example on readme page
- run the app

you should see button `Open Yodlee` and when you click it should initialize and show screen below.

![Screen Shot 2021-01-09 at 12 53 16](https://user-images.githubusercontent.com/818450/104090856-b9673000-5279-11eb-9bcd-5920bca21f0b.png)
